### PR TITLE
Instance sqlite class at worker start

### PR DESCRIPTION
**Pull request by joanhey**
Using sqlite file, still the bottleneck is the I/O but the latency is lower.

But with :memory, exist a noticeable gain.

We can optimize more the sqlite class, to use the prepared statements persistent too.

### CODE REVIEW

**Comment by josephscott** [comment]
I need to give this one more thought.  On startup I see warnings about the database being locked.  That said, all of the tests pass, so it isn't a fatal error.  More of a question of how long processes might have to wait while the database is locked.

Perhaps this should be tied in with providing a busy timeout value - https://www.php.net/manual/en/sqlite3.busytimeout.php

Minor detail, on line 77 there is a space on an empty line.

**Comment by joanhey** [comment]
When we use Workerman, we have a persistent app in memory.
We don't need to instance a class for each request (not all), like a normal php app with php-fpm.

With Sqlite that run in the same host, is less problematic. 
But with a normal db in another server, the difference is very big.

In the TechEmpower benchmark:
Workerman and Ngx-php start with a call to the db class per request, and get ~180K req/s.
Later I changed it to reuse the same db class instanciated at worker start, and get +300K req/s.

If exist a problem, we need to find it, but we are not using a shared nothing php app.
The problem is NOT with instance the class at worker start.

PD: I create almost all PRs to the TechEmpower benchmark, related to the php ecosystem (not only).
And I'm the second contributor to Workerman and Ngx-php.

**Comment by josephscott** [comment]
Right, I understand the difference between the app server model and the php-fpm/shared nothing model.

And I'm not calling into question your qualifications, quite the opposite.  I noticed your work on AdapterMan, which I'm interested in.  At some point I want to see if Workerman + AdapterMan + WordPress will work correctly.

My only pause is that this change generates new warnings, and I want to make sure they are not a sign of new problems.

**Comment by joanhey** [comment]
The problem at start about the database being locked. 
It's because all workers try to create the table with SQL in the sqlite database.

We need to do it before, and call a static init() method just once time.
And perhaps will be better, if this class is all static. I will check the class.

**Comment by josephscott** [comment]
I've got an idea of what is happening.  I'll follow up after a few experiments.

**Comment by josephscott** [comment]
I figured out what was going on.  The busy timeout and WAL need to be turned out as the first operations after hooking up the SQLite DB.  I've made those changes in https://github.com/josephscott/marmerine/commit/a3d62a702bfe1614048ba1862777b3bbe809b852 - so now we should be able to move to the `onWorkerStart` approach.

**Comment by josephscott** [comment]
WAL is always enabled as of https://github.com/josephscott/marmerine/commit/a3d62a702bfe1614048ba1862777b3bbe809b852 - so the `$storage->enable( 'WAL' );` needs to be removed from the diff.

**Comment by josephscott** [comment]
I committed a version of this in https://github.com/josephscott/marmerine/commit/4268fc1927ae7ab02d54f086cb7848f0078ca7f8

Since WAL is now always enabled `$storage->enable( 'WAL' );` just throws an error.

**Comment by josephscott** [comment]
There are no more changes to merge from this, so I'm going to close it.

**Pull request closed without merging**
