### PR TITLE
Update Pest tests

### PR DESCRIPTION
**Pull request by joanhey**
Changed pest.php to Pest.php, or don't work the tests.

CamelCase all tests name files, as it's the default.

Update Pest to v1.22.3

### CODE REVIEW

**Comment by joanhey** [comment]
When this PR is merged, I'll add another PR to run the tests using Github actions.
To have automatic tests with each push and PR.

**Comment by josephscott** [comment]
I like the idea of running the tests via Github actions.

In terms of updating Pest, all of the current tests work as is with latest version of 1.22.3.

**Comment by joanhey** [comment]
It's not about the version, that I'll send another commit to use Caret Version Range.

The change is for the filenames, in php-unit and pest by default are CamelCase (PSR).
If another dev want to help with the tests, he will be lost with naming files.

image

**Comment by joanhey** [comment]
Using `phpunit.xml.dist` now, `phpunit.xml` have preference and is for the user.
Don't exist dir: app and src, so deleted from dist.

**Comment by joanhey** [comment]
`phpunit.xml` if for the user, and need to be in .gitignore.

`phpunit.xml.dist` is for the distributed lib.

**Comment by joanhey** [comment]
Explication about using caret version range.

That 2 libs use Semver, so no breaking compatibility without change a major version number.
When we use an exact version, we are forcing the user to update.

It's like using `php = 8.0.1`, any user using a modern php version will not use this lib.... and need to downgrade.
The same with the dependencies versions.

**Comment by joanhey** [comment]
After merge this PR, I have ready the github action to run the tests of phpstan and pestphp.
And will be faster and easier for all contributors and you like a reviewer.

**Comment by joanhey** [comment]
I have a lot more changes, but with automatic tests will be easier.

**Comment by josephscott** [comment]
I have a hard time imagining that a dev would have a hard time figuring out which file a test is located in.  It isn't like the Pest UI uses a different name in the output from the file name.

That said, I'm not interested in quibbling over this type of style change.  I will go ahead and merge this.

**Pull request merged**
